apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  labels:
    app: django-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-agent
  template:
    metadata:
      labels:
        app: django-agent
    spec:
      containers:
        - image: patrickpk/agent:latest
          name: django-agent
          ports:
            - containerPort: 8001
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: guest
            - name: RABBITMQ_PASSWORD
              value: guest


---

apiVersion: v1
kind: Service
metadata:
  name: django-agent
  labels:
    app: django-agent
spec:
  type: NodePort
  selector:
    app: django-agent
  ports:
    - port: 8001
      targetPort: 8001