apiVersion: apps/v1
kind: Deployment
metadata:
  name: headquaters
  labels:
    app: django-headquaters
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-headquaters
  template:
    metadata:
      labels:
        app: django-headquaters
    spec:
      containers:
        - image: patrickpk/headquaters:latest
          name: django-headquaters
          ports:
            - containerPort: 8000
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: guest
            - name: RABBITMQ_PASSWORD
              value: guest
            - name: ELASTICSEARCH_HOST
              value: elasticsearch
            - name: ELASTICSEARCH_PORT
              value: "9200"

---

apiVersion: v1
kind: Service
metadata:
  name: django-headquaters
  labels:
    app: django-headquaters
spec:
  type: NodePort
  selector:
    app: django-headquaters
  ports:
    - port: 8000
      targetPort: 8000